server:
  port: 8089
spring:
  application:
    name: learntribe-inquisitive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/auth/realms/test-realm
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

